[package]
name = "mandelbrod"
version = "0.1.0"
edition = "2021"

[dependencies]
raylib = {version = "5.0.0", features=["wayland"]}

[profile.dev]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
[profile.release]
debug = true
